policy:
  - id: "default"
    interface: "\\Device\\NPF_{xxx}"  # 修改为正确的网卡接口
    white_ips:
      - "127.0.0.1"
      - "192.168.1.1"
    white_ports:
      - "22"
      - "80"
      - "443"

service:
  - id: "ssh"
    service_name: "SSH Service"
    local_port: 2222
    backend_host: "127.0.0.1"
    backend_port: 2223

  - id: "mysql"
    service_name: "MySQL Service"
    local_port: 3306       
    backend_host: "127.0.0.1"
    backend_port: 3366      # Server 监听 3366

  - id: "redis"
    service_name: "Redis Service"
    local_port: 6379        
    backend_host: "127.0.0.1"
    backend_port: 6380      # Server 监听 6380

  - id: "web"
    service_name: "Web Service"
    local_port: 8080
    backend_host: "127.0.0.1"
    backend_port: 8081
